### ISSUE TITLE
Supporting directed edges

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/spras#107]
@ntalluri is starting to work on incorporating directed edges, so we're talking about that at our meeting today. We realized there are a number of issues, so we wanted to start a conversation about them. 

1. Some algorithms support directed edges, some don't. Issue #28 suggested that perhaps this isn't an algorithm-level decision (and shouldn't be in the CONFIG file as a user option), but we should decided on how each algorithm supports directed vs. undirected edges. @ntalluri  is collecting information about each algorithm, which will be very helpful.
2. Directed vs. undirected edges is actually a _data_ attribute (the interactome). Further, if a method supports either directed or undirected edges, then this information must be used in the `generate_inputs()` function to prepare the network files (unless it's passed directly to the algorithm as an argument). For example, if a network is undirected, then `RWR` should convert it to a bidirected graph before running. If it's directed, `RWR` doesn't need to convert it. (The decision that `RWR` runs on a bidirected network is one that we, the developers, made). 
3. Maybe a general table like the one below will help us make these decisions for all algorithms?

|  Network Type | Algorithm Runs on Undirected Only | Algorithm Runs on Directed Only | Algorithm Runs on Dir or Undir |
| --- | --- | --- | --- |
| Undirected | Ready to Run | Ignore? Make Bi-Directed? | Ready to Run |
| Directed | Ignore? Make Undirected? | Ready to Run | Ready to Run |
| Mixed | TODO | TODO | TODO |

**Comment by ntalluri** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a351191d-7fff-7cda-7b33-9cc5930ae82e"><div dir="ltr" style="margin-left:-72pt;" align="left">

Algorithm Directionality Inputs | MEOIt supports partially directed graphs, but the format is different from the way we are probably going to set up the input files with. The file format looks like this https://github.com/agitter/meo/blob/master/sampleEdges.txt. It uses a pp to represent undirected edges, and pd for directed edges.Based on this issue, https://github.com/Reed-CompBio/spras/issues/47#issuecomment-890094018, MEO may not be able to support pairs of bidirectional edges ( as in an edge from u,v and v,u). There is a chance that MEO assumes that it should just be an undirected edge (pp) instead. Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edges.Omics Integrator 1 Omics integrator 1 supports partially directed edges using the file format that works in the fork: https://github.com/agitter/spras/tree/directed-oi1/input#edge-file.The format works by adding a fourth column for directionality to the input network file. It will take a U for an undirected edge and a D for a directed edge from the first to second columnOmics Integrator 2In omics integrator 2, it mentions in graph.py that “ # `edges`: a 2D int64 array. Each row (of length 2) specifies an undirected edge in the input graph. The nodes are labeled 0 to n-1, where n is the number of nodes. “Based on this, it specified that each row of the array represents an undirected edge in the input graph, so I believe that it only takes undirected edgesMin Cost FlowBased on my research, OR Tools MCF is designed for directed graphs, not undirected. When we give it an input network, when an edge (arc) is added, it has a source node (which is the tail) and a target node (which is the head), so flow is only allowed to move from the source to the targetTo use MCF on an undirected graph, we can convert the undirected edge into 2 directed edges, one in each direction. The capacity would remain the same and this would infact show the flow moving freely in both directions.Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edgesIn mincostflow code currently, the code makes a given edge have bidirectionality: https://github.com/gitter-lab/min-cost-flow/blob/main/minCostFlow.py#L46-L47PathlinkerThe version of Pathlinker that is wrapped in SPRAS works with directed edges that also have an associated weight. An edge is represented with a head and tail node in the current input network format, which indicates the direction of the interaction between two nodes. If we want to put an “undirected edge” - meaning an interaction that is bidirectional - Pathlinker would require for both paths to be put into the input network file (one for each direction of the interaction)This is similar to how Min Cost Flow could take in the input after conversionRelevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edgesAll Pairs Shortest PathsThe algorithm appears to be capable of accepting only undirected edges and allowing bidirectionally if an edge and its reverse are placed in the input network.The code uses nx.read_weighted_edgelist() and nx.Graph() which both are used for undirected graphsnx.shortest_path can work on both undirected and directed edges, but it seems by the rest of the code that it is creating an undirected graph DominoBased on the build_network function in domino, it created an undirected graph using nx.Graph() and the provided input file. The function will read the 1st and 3rd columns from the file (which are node pairs that make up the edge). Each of these edges will be added to the undirected graph with a score (if there is a unique node). When it is run through the algorithm, it will see that bidirectional edges are equivalent. This means we can use bidirectional edges in the input.RWRFrom eric: Regarding the RWR (Random Walk with Restarts) process, it takes into account both directed and undirected edges in its execution. When encountering undirected edges, RWR converts them into two directed edges, one in each direction to represent the relationship between the nodes more accurately.This explanation doesn’t seem to be right, based on the code I looked at. It seems to only be able to handle directional edgesGenerate_graph is constructing a directing graph (nx.DiGraph()) using the nodes and edges provided to it from the other methodsIn generate_nodes_and_edges, it seems that it is going line by line and adding what is in the provided edge file to the set of nodes and the array of edges without adding the reverse edge to the set of nodes and array of edgesIt truly seems that the code expects the edges provided are already directed and are not converted to be bidirectionalTieDieFrom Eric: TieDIE deals specifically with directed edges, which are represented in the format A -a> B where -a> stands for activation. While the TieDIE repository provides examples with various types of interactions, such as inhibitions, SPRAS focuses solely on considering activation interactions in the interactome. This limitation is due to TieDIE's requirement to discern the activating relationships between genes, which is crucial for its execution. As a result, undirected edges are not used in the TieDIE process.parser.add_option("-n","--network",dest="network",action="store",default="superpathway.sif",help="\.sif network file for the curated pathway to search. <source>   <(-a>,-a\|,-t>,-t\|,-component>)> <target>")Based on <(-a>,-a\|,-t>,-t\|,-component>)> from the actual tiedie code, this takes in these interactions, but in tiedie.py in spras only allows for -a>, so we only allow for activated directed edgesBowTieBuilder
-- | --


</div></b>

**Comment by ntalluri** [comment]
| MEO | Omics Integrator 1 | Omics Integrator 2 |  MCF | Pathlinker | All Pairs Shortest Paths | Domino | RWR | TieDie |
|------------------------------------------------------------------------------------------------------------------|

**Comment by ntalluri** [comment]
| Algorithm                | Description                                                                                                                                                                                                                                            |
|--------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| MEO                      | Supports partially directed graphs with a different format from our potential input files setup. The format can be found [here](https://github.com/agitter/meo/blob/master/sampleEdges.txt). It might not support pairs of bidirectional edges properly. |
| Omics Integrator 1       | Supports partially directed edges using the file format in this [fork](https://github.com/agitter/spras/tree/directed-oi1/input#edge-file). It uses a fourth column for directionality: U for undirected and D for directed edges.                    |
| Omics Integrator 2       | Based on `graph.py`, it only takes undirected edges. Each row of the array represents an undirected edge in the input graph.                                                                                                                         |
| Min Cost Flow            | OR Tools MCF is designed for directed graphs only. To handle undirected graphs, we can convert the undirected edge into 2 directed edges. The code for bidirectionality can be found [here](https://github.com/gitter-lab/min-cost-flow/blob/main/minCostFlow.py#L46-L47). |
| Pathlinker               | The version wrapped in SPRAS deals with directed edges with weights. For undirected edges, both paths (both directions) must be added to the input.                                                                                                     |
| All Pairs Shortest Paths | Accepts only undirected edges and can allow bidirectionality if an edge and its reverse are in the input. The code uses `nx.read_weighted_edgelist()` and `nx.Graph()`.                                                                                  |
| Domino                   | Creates an undirected graph. Bidirectional edges in the input are equivalent.                                                                                                                                                                           |
| RWR                      | Seems to only handle directional edges based on the code. The edges provided are expected to be directed and aren't converted to be bidirectional.                                                                                                      |
| TieDie                   | Deals specifically with directed edges. Undirected edges are not used in the process. Based on tiedie.py in spras, only activated directed edges are allowed.                                                                                           |
| BowTieBuilder            | N/A                                                                                                                                                                                                                              |

**Comment by ntalluri** [comment]
| Algorithm                | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|--------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| MEO                      | Supports partially directed graphs, but the format is different from the way we are probably going to set up the input files with. The file format looks like this [sampleEdges.txt](https://github.com/agitter/meo/blob/master/sampleEdges.txt). It uses a pp to represent undirected edges, and pd for directed edges. Based on this [issue](https://github.com/Reed-CompBio/spras/issues/47#issuecomment-890094018), MEO may not be able to support pairs of bidirectional edges ( as in an edge from u,v and v,u). There is a chance that MEO assumes that it should just be an undirected edge (pp) instead. Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edges.  |
| Omics Integrator 1       | Omics integrator 1 supports partially directed edges using the file format that works in the fork: [directed-oi1](https://github.com/agitter/spras/tree/directed-oi1/input#edge-file). The format works by adding a fourth column for directionality to the input network file. It will take a U for an undirected edge and a D for a directed edge from the first to second column.                                                                                                                                                                                                                                                                                                                                  |
| Omics Integrator 2       | In omics integrator 2, it mentions in graph.py that “ # `edges`: a 2D int64 array. Each row (of length 2) specifies an undirected edge in the input graph. The nodes are labeled 0 to n-1, where n is the number of nodes. “ Based on this, it specified that each row of the array represents an undirected edge in the input graph, so I believe that it only takes undirected edges.                                                                                                                                                                                                                                                                    |
| Min Cost Flow            | Based on my research, OR Tools MCF is designed for directed graphs, not undirected. When we give it an input network, when an edge (arc) is added, it has a source node (which is the tail) and a target node (which is the head), so flow is only allowed to move from the source to the target. To use MCF on an undirected graph, we can convert the undirected edge into 2 directed edges, one in each direction. The capacity would remain the same and this would infact show the flow moving freely in both directions. Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edges. In mincostflow code currently, the code makes a given edge have bidirectionality: [minCostFlow.py](https://github.com/gitter-lab/min-cost-flow/blob/main/minCostFlow.py#L46-L47) |
| Pathlinker               | The version of Pathlinker that is wrapped in SPRAS works with directed edges that also have an associated weight. An edge is represented with a head and tail node in the current input network format, which indicates the direction of the interaction between two nodes. If we want to put an “undirected edge” - meaning an interaction that is bidirectional - Pathlinker would require for both paths to be put into the input network file (one for each direction of the interaction). This is similar to how Min Cost Flow could take in the input after conversion. Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edges.                                                           |
| All Pairs Shortest Paths | The algorithm appears to be capable of accepting only undirected edges and allowing bidirectionally if an edge and its reverse are placed in the input network. The code uses nx.read_weighted_edgelist() and nx.Graph() which both are used for undirected graphs. nx.shortest_path can work on both undirected and directed edges, but it seems by the rest of the code that it is creating an undirected graph.                                                                                                                                                                                                                                                                    |
| Domino                   | Based on the build_network function in domino, it created an undirected graph using nx.Graph() and the provided input file. The function will read the 1st and 3rd columns from the file (which are node pairs that make up the edge). Each of these edges will be added to the undirected graph with a score (if there is a unique node). When it is run through the algorithm, it will see that bidirectional edges are equivalent. This means we can use bidirectional edges in the input.                                                                                                                                                                 |
| RWR                      | From eric: Regarding the RWR (Random Walk with Restarts) process, it takes into account both directed and undirected edges in its execution. When encountering undirected edges, RWR converts them into two directed edges, one in each direction to represent the relationship between the nodes more accurately. This explanation doesn’t seem to be right, based on the code I looked at. It seems to only be able to handle directional edges. Generate_graph is constructing a directing graph (nx.DiGraph()) using the nodes and edges provided to it from the other methods. In generate_nodes_and_edges, it seems that it is going line by line and adding what is in the provided edge file to the set of nodes and the array of edges without adding the reverse edge to the set of nodes and array of edges. It truly seems that the code expects the edges provided are already directed and are not converted to be bidirectional. |
| TieDie                   | From Eric: TieDIE deals specifically with directed edges, which are represented in the format A -a> B where -a> stands for activation. While the TieDIE repository provides examples with various types of interactions, such as inhibitions, SPRAS focuses solely on considering activation interactions in the interactome. This limitation is due to TieDIE's requirement to discern the activating relationships between genes, which is crucial for its execution. As a result, undirected edges are not used in the TieDIE process. parser.add_option("-n","--network",dest="network",action="store",default="superpathway.sif",help="\.sif network file for the curated pathway to search. <source> <(-a>,-a|,-t>,-t|,-component>)> <target>") Based on <(-a>,-a|,-t>,-t|,-component>)> from the actual tiedie code, this takes in these interactions, but in tiedie.py in spras only allows for -a>, so we only allow for activated directed edges.                                                                                          |
| BowTieBuilder            | N/A                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

**Comment by ntalluri** [comment]
MEO

- It supports partially directed graphs, but the format is different from the way we are probably going to set up the input files with. The file format looks like this https://github.com/agitter/meo/blob/master/sampleEdges.txt. It uses a pp to represent undirected edges, and pd for directed edges.
- Based on this issue, https://github.com/Reed-CompBio/spras/issues/47#issuecomment-890094018, MEO may not be able to support pairs of bidirectional edges ( as in an edge from u,v and v,u). There is a chance that MEO assumes that it should just be an undirected edge (pp) instead. 
- Relevant to the discussion of converting undirected graphs to directed graphs with duplicated directed edges.

**Comment by ntalluri** [comment]
Omics Integrator 1

- Omics integrator 1 supports partially directed edges using the file format that works in the fork: https://github.com/agitter/spras/tree/directed-oi1/input#edge-file.
- The format works by adding a fourth column for directionality to the input network file. It will take a U for an undirected edge and a D for a directed edge from the first to second column

**Comment by ntalluri** [comment]
Omics Integrator 2

- In omics integrator 2, it mentions in graph.py that “ # `edges`: a 2D int64 array. Each row (of length 2) specifies an undirected edge in the input graph. The nodes are labeled 0 to n-1, where n is the number of nodes. “
- Based on this, it specified that each row of the array represents an undirected edge in the input graph, so I believe that it only takes undirected edges

**Comment by ntalluri** [comment]
MEO 
- can deal with fully directed, fully undirected, and mixed graphs

Pathlinker
- deals with fully directed graphs

Min Cost Flow
- deals with fully directed graphs

Omics Integrator 1
- can deal with fully directed, fully undirected, and mixed graphs

Omics Integrator 2
- can deal with fully undirected graphs

Domino
- can deal with fully undirected graphs

RWR: 
- can deal with fully directed graphs

TieDie: 
- can deal with fully directed graphs

BowTieBuilder:
- N/a

**Comment by ntalluri** [comment]
Network Type | Algorithm Runs on Undirected Only | Algorithm Runs on Directed Only | Algorithm Runs on Dir or Undir |
| --- | --- | --- | --- |
| Undirected | Ready to Run | Make Bi-Directed | Ready to Run |
| Directed | Make Undirected| Ready to Run | Ready to Run |
| Mixed| Make directed edges into undirected (not bidirectional | Make undirected edges into bidirectional | Ready to Run |

**Comment by ntalluri** [comment]
Algorithms that work with bidirectional edges:
MCF

that don't:
MEO

**Comment by ntalluri** [comment]
### First Idea
Input file format ideas:

Type 1: 

A	B	1
C	B	1
- no directionality added by user
- the code will add a undirected column of directionality 

Type 2:

A	B	1	D
B	C	1 	U
- this can be a mix of directionality

### Second idea
- we can keep the two file formats, but in the config file add a line where a user can mark true/false for directionality (overall) rather than per algorithm. 
- with this, we can do a series of checks. If marked true we assume there are 4 columns, and if not we give back an error. If false, then we assume 3 columns and no directionality. (however do we still assume the graph is undirected)

**Comment by ntalluri** [comment]
Parts of the code that will need to change

**DATASET.PY:**
self.interactome = pd.read_table(os.path.join(data_loc,interactome_loc), header=None)
        
num_cols = self.interactome.shape[1]
        
	if num_cols == 3:
           
       	self.interactome.columns = ["Interactor1", "Interactor2", "Weight"]
	- with this way, we would require that a user would need to add column of direction where it is all undirected
		
	or 
	
	self.interactome.columns = ["Interactor1", "Interactor2", "Weight"]
	self.interactome[‘Direction’] = ‘U’
	- with this way it will make it easier for the generate inputs implementations since the inputs will already be transformed to be in the new default input style 
	- it will provide a default Direction of undirected (‘U’) for every edge if not provided
	SHOULD IT BE A DEFAULT OF U OR D?
	- my opinion is U

        elif num_cols == 4:
            self.interactome.columns = ["Interactor1", "Interactor2", "Weight", "Direction"]
        
	else:
            raise ValueError(f'edge_files must have three or four columns but found {num_cols}')


**CONFIG FILE:**
- we should remove the directed: true/ false from each algorithm
- we already expect there to be a directed column where we default to an undirected graph (as of right now)

**Util.py**
- will need to add functions that can be called in generate inputs depending on overall format transformation ( based on table above ), however unsure of what these functions will fully do at the moment
- MEO might be a special case?

**Other parts to change:**
- each algorithm's generate inputs and parse outputs will need to change
- generate inputs will have to use the new functions from util.py to help create format
- parse outputs will need to add the directionality if the column is added based on how the algortihm deals with directionality. (Example: if an algorithm only deals with directed edges, and we take in a mixed network, we output a network with directionality of all D in the direction column)

**Comment by ntalluri** [comment]
### Util.py functions

There is a similarity between completely directed and undirected graphs based on the existing algorithm formats. 

- Pathlinker, Min-Cost Flow, and RWR are all completely directed graphs with a similar structure. TieDie is likewise completely directed, but the only difference is that it contains a separator between each node (currently does this, the code may change?). 
- Both Omics Integrator 2 and Domino are completely undirected, with the only difference in format being a separator between each node in Domino. 

It is possible to build two functions: 
- fullyDirectedConversion(universal_input, sep(?))
- fullyUndirectedConversion(universal_input, sep(?))
A user will be able to call one of these functions with an optional separator, which will turn the universal input into the appropriate graph depending on the graph conversion logic from the table above and whether or not it includes a separator.

**Comment by ntalluri** [comment]
### Util.py functions for parse outputs 

**A df that is provided to these functions should be modified to the point where it can call these functions last, with the respected columns (if necessary) still present, so that the direction column can be included in the outputs.** 

For the fully directed and fully undirected algorithms, we can have two functions in util.py:
add_direction_column_directed(df)
- this would take the df that is already being modified and add a new direction column of 'D's, returning the transformed df
add_direction_column_undirected(df)
- this would take the df that is already being modified and add a new direction column of 'U's, returning the transformed df.
- 
For the mixed algorithms, we can have 1 function 
add_direction_column_mixed(df, directed_dlim, undirected_dlim, column_loc(?))
- this takes the df and, and by using the directionality's column location,  it adds a 'D' or 'U' per row dependent on the directed or undirected delimiter.

**Comment by ntalluri** [comment]
### Dealing with interpreting the input network

**Config.yaml** 
We can put per dataset a graphtype: "mixed"/"undirected"/"directed" 
- We are able to allow a user to have the absence of the fourth column and add it in depending on the undirected/directed marking. This addresses the possibility that a user gives a dataset with no specification on the nature of the edges; rather than requiring the user to edit the original dataset, we enable the user to specify the type in the config and we can make that modification for them (if needed). By knowing the type overall will help with the graph conversion in generate inputs. If the user adds the fourth column of directionality, we can still check that it exists and then allow it to pass. (Do we want to check if the whole column is directed/undirected?)
- If a graph has mixed directionality, the user must enter it manually. If "mixed" is selected, we can ensure and check that the network has four columns (Do we want to check that the column is a mix of only 'D' and 'U's). If there are three columns but "mixed" is selected, we can flag an error and notify them before executing the entire program. 

**Dataset.py**
```

self.interactome = pd.read_table(os.path.join(data_loc,interactome_loc), header=None)
        num_cols = self.interactome.shape[1]
        if num_cols == 3:
            # TODO: it may be easier for the generate_inputs implementations if this is always transformed to
            # have a default Direction directed or undirected based on what is written in the config file
            self.interactome.columns = ["Interactor1", "Interactor2", "Weight"]
        elif num_cols == 4:
            self.interactome.columns = ["Interactor1", "Interactor2", "Weight", "Direction"]
        else:
            raise ValueError(f'edge_files must have three or four columns but found {num_cols}')
```

**Generate Inputs**

- Even if we have the fourth row for a fully directed, fully directed, or mixed graph, the data must be modified to operate with the algorithms. To deal with the logic from the conversion table and what functions to call or columns to add, we need to know the kind of graph.

**Comment by agitter** [comment]
> Omics Integrator 2 can deal with fully undirected graphs

I looked at its code as well and agree it uses undirected graphs. It has NetworkX Graph objects, which are undirected, and uses [pcst_fast solver](https://github.com/fraenkel-lab/pcst_fast), which supports undirected graphs.

Now that you have done all of this work, I suggest that your pull request include some of this information in the Class or `generate_inputs` docstrings of each method. For instance, we can document what you learned about the method's support for undirected, directed, and mixed graphs and the assumptions SPRAS makes when preparing input graphs. We could even document the expected raw input file format.

I agree with your updated table about the behavior for each type of algorithm on each type of graph.

We may want to put the helper functions for converting graphs in `Dataset.py` instead of `util.py`. `util.py` is already crowded. I see two types of operations needed:
- one takes the existing graph and coverts edge types (e.g. undirected to pairs of directed or directed to undirected)
- one organizes the node ordering and separators

I think it will help reusability and implementation to keep those separated. I'm imagining less algorithm-specific logic and suggest making the 3 vs. 4 column input file handling standardized when the file is first loaded by `Dataset.py` so by the time `generate_inputs` accesses the dataframe it will always have 4 columns.

In our last meeting we talked about using the config file to specify whether the 3 column format is all directed or undirected edges. That would be a nice feature. However, I propose keeping this simple at first and assuming the 3 column format is always undirected. If there is demand for this extra flexibility, we could easily add it later.

**Comment by agitter** [comment]
@annaritz we noticed that most of SPRAS currently works with undirected graphs, but PathLinker uses directed graphs. We are currently taking the input graph to SPRAS (which the user likely assumes is undirected) and then passing those edges to PathLinker, which interprets them as directed edges. That seems wrong to me.

@ntalluri's enhancements will fix this behavior, but the current PathLinker wrapper is not ideal in this respect.

Separately, we discussed that there isn't a practical need for a helper function to make a directed graph undirected. The algorithms that would use this instead can simply drop the fourth column with the directionality information.

**Comment by annaritz** [comment]
Good catch! Yes, you're right. we should be making the (assumed undirected) input graph bidirected for PathLinker.

**Comment by ntalluri** [comment]
### Updating ML Post Processing

Two methods to change: 
- summarize_networks
- ensemble_network
* test_ml.py will also need to change

The edges are dealt within for in the index, and the columns are the algorithms. The rest of the methods are not dependent on the edges/index (the first line of code for each method drops the index) so nothing has to change for them. 

**ml.py**
- add a UNDIR_CONST and DIR_CONST to replace the current NODE_SEP (since this assumes everything is undirected)

**summarize_networks**
- when making the edge_tuples, now take into account the direction in the fourth column. Add the directionality constant accordingly. 

**ensemble_network**
- At the moment, it means across edges (axis 1) and returns the edge-pair and frequency. It then proceeds to divide the two nodes into Node1 and Node2. If I do this now, the txt file would lose all directionality unless I add a Direction column to each line rather than maintaining it in the edge-pair and frequency form, which already has the UNDIR_CONST and DIR_CONST, which sounds like random extra computations for the same benefit. 
- so I think my plan is to keep it in the edge-pair and frequency form and write that out

**Comment by ntalluri** [comment]
### summary.py and graphspace.py

https://stackoverflow.com/questions/55496703/is-it-possible-to-add-undirected-and-directed-edges-to-a-graph-object-in-network

**Comment by ntalluri** [comment]
For network x digraphs and graphs, it doesn't allow for multiple parallel edges. With that in mind, I need to test this on the algorithms to see which ones fail.

**Comment by ntalluri** [comment]
Reminder: all the outputs of MEO are **directed**. MEO can deal with mixed directionality inputs.
