### ISSUE TITLE
`networkx` version potential incompatibilty

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/spras#13]
In the `output-analysis` branch, we are beginning to use `networkx` functions. However, v2 is not compatible with v1.11. Should the version be specified in a `requirements.txt` file?

**Comment by agitter** [comment]
Yes, I agree that we should specify compatible package versions for all external packages we depend on.  For networkx, I propose we have our code be compatible with the latest version (2.5.x).

The `oi2` branch adds a conda environment file `environment.yml` instead of a `requirements.txt` file and specifies `networkx=2.5`.  It then runs the pytest tests in that environment.  Would that address this issue?

**Comment by annaritz** [comment]
Yes, I think this does. Closing the issue for now.
