### ISSUE TITLE
Docker makes output files as root on linux 

### ISSUE THREAD

**Issue by csmagnano** [Reed-CompBio/spras#22]
This is a known issue which happens with other docker users (there is a good discussion on the issue [here](https://github.com/moby/moby/issues/3206))

When docker runs commands, it runs them as root. Which means that all output files are owned by root. This causes permission errors when Snakemake then tries to touch the files after the reconstruct rule.

Trying to run the docker command as a different user gives permission errors for accessing the omics integrator scripts. 

What I've done for now is added a second docker run command which changes ownership of all output files to the current user, gotten with `os.getuid()` in 5cc19153a36afb12c63ea4942a326ce1d3b96c11. However, this might not work well on other operating systems and requires every new method to use a similar approach. 

There are some more complex solutions which involve creating a new user within the docker container [here](https://vsupalov.com/docker-shared-permissions/) and [here](https://denibertovic.com/posts/handling-permissions-with-docker-volumes/) we could consider.

**Comment by agitter** [comment]
I need to work on this in order to standardize a new interface for running in either Singularity or Docker for #49.

I read through the linked resources above and think that our current approach of running `chown` in the container may be the best option.  We can't build a new container for every user and system because we are going to distribute our images.  Changing the user inside the container with a wrapper script and gosu is a nice solution.  However, we're already using a custom entrypoint to active the conda environment inside the container.
